### ISSUE TITLE
support non-github package?

### ISSUE THREAD

**Issue by cynial** [jduepmeier/binary-package-manager#21]
bpm is great!

Is it possible to support non-github package?

Something like:

1. kubectl: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
2. minikube: https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64

**Comment by jduepmeier** [comment]
To support other places for packages it is required that you can receive a list of versions to determine the latest version.

I have plans to add gitlab and maybe a generic provider.

For the given examples it is already possible.
1. For kubectl there is the https://github.com/kubernetes/kubernetes repo. In the config for a package you can add a seperate download url.
```yaml
---
schema_version: 2
name: kubectl
provider: github.com
url: github.com/kubernetes/kubernetes
goos:
  linux: linux
goarch:
  amd64: amd64
archive_format: ""
bin_pattern: ""
download_url: "https://dl.k8s.io/release/${version}/bin/${goos}/${goarch}/kubectl"
```

2. For minikube there is a github project with releases, too: https://github.com/kubernetes/minikube
