### ISSUE TITLE
".tar.xz" package support

### ISSUE THREAD

**Issue by cynial** [jduepmeier/binary-package-manager#37]
The installation package for node is  `.tar.xz` format (https://nodejs.org/dist/v18.15.0/node-v18.15.0-linux-x64.tar.xz)

I tried to use `archive_format: tar` setting, but it return `archive/tar: invalid tar header` error. 

How can I extract `.tar.xz` package? Thanks.

**Comment by jduepmeier** [comment]
xz is a compression algorithmus which is currently not supported. The golang standard library (https://pkg.go.dev/compress) has no xz therefore I need to find a decompression library for golang first.

**Comment by jduepmeier** [comment]
is released with 0.4.0

I tested the library with the following package definition:
```yaml
schema_version: 2
name: node
provider: github.com
url: github.com/nodejs/node
goos:
  linux: linux
goarch:
  amd64: x64
asset_pattern: ""
archive_format: tar.xz
bin_pattern: "^.*/bin/node$"
download_url: "https://nodejs.org/dist/${version}/node-${version}-${goos}-${goarch}.tar.xz"
```
